version: '3.4'

services:
  taskiano:
    image: taskiano
    build:
      context: taskiano
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
