name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 22 * * 3'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install deps
        run: yarn install
        working-directory: ./taskiano
        
      - name: Linting
        run: yarn lint
        working-directory: ./taskiano

      # - name: Test
      #   run: yarn test
        
      - name: Build
        run: yarn build
        working-directory: ./taskiano

      - name: SonarCloud Scan
        # You may pin to the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        uses: SonarSource/sonarcloud-github-action@v1.6
        with:
          # Additional arguments to the sonarcloud scanner
          # args: # optional
          projectBaseDir: ./taskiano
